### PR TITLE
Merging base of documentation in preparation for the gh-pages branch

### PR DESCRIPTION
**Pull request by pmudry**

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks : D

**Comment by pmudry** [comment]
I can't pull request the gh-pages branch.... I guess you'll have to do it
manually from the SpinalHDL repo directly...
Good luck!

**Comment by Dolu1990** [comment]
No problems, i don't know what i have done, but it's fine now ^^

**Comment by Dolu1990** [comment]
Did you remember having web pages displayed in "raw text/no css" mode when you run gh-pages localy ?

**Comment by Dolu1990** [comment]
Ahhh it's fine now, had to comment out url: http://pmudry.github.io  in _config.yml

**Pull request merged**
